package readline

// emacsKeys are the default keymaps in Emacs mode
var emacsKeys = keymap{
	"^M":   "accept-line",
	"^A":   "beginning-of-line",
	"^B":   "backward-char",
	"^D":   "delete-char-or-list",
	"^E":   "end-of-line",
	"^F":   "forward-char",
	"^G":   "send-break",
	"^I":   "expand-or-complete",
	"^K":   "kill-line",
	"^L":   "clear-screen",
	"^N":   "down-line-or-history",
	"^P":   "up-line-or-history",
	"^O":   "accept-line-and-down-history",
	"^T":   "transpose-chars",
	"^U":   "kill-whole-line",
	"^V":   "quoted-insert", // TODO WHAT IS THIS ?
	"^W":   "backward-kill-word",
	"^Y":   "yank",
	"^X^B": "vi-match-bracket",
	"^X^E": "vi-edit-command-line",
	"^X^K": "kill-buffer",
	"^X^N": "infer-next-history",
	"^X^O": "overwrite-mode",
	"^X^U": "undo",
	"^X^V": "vi-cmd-mode",
	"^X^X": "exchange-point-and-mark",
	"^Xu":  "undo",

	// TODO: ^Xr ^Xs incremental-search-history. same as CtrlR above.
	// TODO: CtrlR CtrlS incremental-search-history.

	"^[^D":   "list-choices",
	"^[^G":   "send-break",
	"^[^H":   "backward-kill-word",
	"^[^I":   "self-insert-unmeta",
	"^[^J":   "self-insert-unmeta",
	"^[^L":   "clear-screen",
	"^[^M":   "self-insert-unmeta",
	"^[^[OA": "history-search",
	"^[^[OB": "menu-select",
	"^[^[[A": "history-search",
	"^[^[[B": "menu-select",
	"^[^_":   "copy-prev-word",
	"^@":     "set-mark-command",
	// "^[ ":  "expand-history",
	// "^[!":  "expand-history",
	`^["`: "quote-region",
	"^['": "quote-line",
	"^[-": "neg-argument",
	// "^[$":  "spell-word",
	// "^[.":  "insert-last-word",
	"^[<": "beginning-of-buffer-or-history",
	"^[>": "end-of-buffer-or-history",
	"^[A": "accept-and-hold",
	"^[B": "backward-word",
	"^[C": "capitalize-word",
	"^[D": "kill-word",
	"^[F": "forward-word",
	// "^[G": "get-line",
	// "^[H": "run-help",
	"^[L":     "down-case-word",
	"^[N":     "history-search-forward",
	"^[P":     "history-search-backward",
	"^[Q":     "push-line",
	"^[S":     "spell-word",
	"^[T":     "transpose-words",
	"^[U":     "up-case-word",
	"^[W":     "copy-region-as-kill",
	"^[[1;3A": "history-search",
	"^[[1;3B": "menu-select",
	"^[[1;5C": "forward-word",
	"^[[1;5D": "backward-word",
	"^[[200~": "bracketed-paste",
	"^[[3;5~": "kill-word",
	"^[[3~":   "delete-char",
	"^[[5~":   "history-search",
	"^[[6~":   "menu-select",
	"^[[A":    "up-line-or-search",
	"^[[B":    "down-line-or-select",
	"^[[C":    "forward-char",
	"^[[D":    "backward-char",
	"^[[Z":    "menu-select",
	// "^[_":     "insert-last-word",
	"^[a": "accept-and-hold",
	"^[b": "backward-word",
	"^[c": "capitalize-word",
	"^[d": "kill-word",
	"^[f": "forward-word",
	// "^[g":     "get-line",
	// "^[h":     "run-help",
	"^[l": "ls^J",
	"^[m": "copy-prev-shell-word",
	"^[n": "history-search-forward",
	"^[p": "history-search-backward",
	// "^[q": "push-line",
	"^[t": "transpose-words",
	"^[u": "up-case-word",
	"^[w": "kill-region",
	// "^[x": "execute-named-cmd",
	// "^[y":     "yank-pop",
	// "^[z":  "execute-last-named-cmd",
	"^[|":         "vi-goto-column",
	"^?":          "backward-delete-char",
	"^[^?":        "backward-kill-word",
	"^_":          "undo",
	" ":           "space",
	"[!-~]":       "self-insert", // Any non-empty, non-modified key (no control sequences)
	"(\x1b[0-9])": "digit-argument",
	// "\M-^@"-"\M-^?": "self-insert",
}
